project:
  type: website

website:
  title: "Drew Haugen"
  site-url: https://drew-haugen.netlify.app/
  description: "Drew Haugen's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/drewhaugen
      - icon: twitter
        href: https://twitter.com/Drew_Haugen
format:
  html:
    theme: flatly
    css: styles.css
    code-link: true

comments:
  giscus:
    repo: drewhaugen/drewhaugenblog


editor: source

